// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"microservices/ent"
)

type AccessToken struct {
	AccessToken    string `json:"accessToken"`
	AccessExpireAt int64  `json:"accessExpireAt"`
}

type Login struct {
	Refresh *RefreshToken `json:"refresh"`
	Access  *AccessToken  `json:"access"`
	User    *ent.User     `json:"user"`
}

type RefreshToken struct {
	RefreshToken    string `json:"refreshToken"`
	RefreshExpireAt int64  `json:"refreshExpireAt"`
}
